
```sql
-- ===================================================================
-- COMPLETE SUPABASE DATABASE SETUP FOR MAYA CHAT APPLICATION V8 (FINAL)
-- This script creates a clean, working database setup based on your previous working app
-- Run this entire script in your Supabase SQL Editor
-- ===================================================================

-- STEP 1: CLEAN UP THE OLD ENVIRONMENT
DROP TABLE IF EXISTS "messages_log" CASCADE;
DROP TABLE IF EXISTS "ai_profile_settings" CASCADE;
DROP TABLE IF EXISTS "ad_settings" CASCADE;
DROP TABLE IF EXISTS "ai_media_assets" CASCADE;
DROP TABLE IF EXISTS "daily_activity_log" CASCADE;
DROP TABLE IF EXISTS "app_configurations" CASCADE;
DROP TABLE IF EXISTS "admin_status_display" CASCADE;
DROP TABLE IF EXISTS "managed_demo_contacts" CASCADE;
DROP TABLE IF EXISTS "analytics_data" CASCADE;
DROP TABLE IF EXISTS "user_sessions" CASCADE;
DROP TABLE IF EXISTS "chat_contexts" CASCADE;
DROP TABLE IF EXISTS "user_conversations" CASCADE;

-- Drop functions if they exist
DROP FUNCTION IF EXISTS "update_updated_at_column"() CASCADE;
DROP FUNCTION IF EXISTS "get_daily_message_counts"(DATE) CASCADE;
DROP FUNCTION IF EXISTS "get_daily_active_user_counts"(DATE) CASCADE;
DROP FUNCTION IF EXISTS "log_daily_activity_optimized"(TEXT, TEXT, TEXT) CASCADE;
DROP FUNCTION IF EXISTS "cleanup_expired_contexts"() CASCADE;
DROP FUNCTION IF EXISTS "get_chat_analytics"(INTEGER) CASCADE;

-- ===================================================================
-- STEP 2: ENABLE EXTENSIONS
-- ===================================================================
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ===================================================================
-- STEP 3: CREATE ALL TABLES
-- ===================================================================

-- Messages log table for analytics
CREATE TABLE IF NOT EXISTS public.messages_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  message_id TEXT,
  sender_type TEXT, -- 'user' or 'ai'
  chat_id TEXT,     -- e.g., 'kruthika_chat'
  text_content TEXT,
  has_image BOOLEAN DEFAULT FALSE
);

-- Daily activity log for user analytics
CREATE TABLE IF NOT EXISTS public.daily_activity_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_pseudo_id TEXT NOT NULL,
  activity_date DATE NOT NULL,
  chat_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  CONSTRAINT unique_user_activity_per_day_per_chat UNIQUE (user_pseudo_id, activity_date, chat_id)
);

-- App configurations table for all settings
CREATE TABLE IF NOT EXISTS public.app_configurations (
  id TEXT PRIMARY KEY,
  settings JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Ad settings table (your working structure)
CREATE TABLE IF NOT EXISTS public.ad_settings (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    
    -- Global ad settings
    ads_enabled_globally BOOLEAN DEFAULT true,
    max_direct_link_ads_per_day INTEGER DEFAULT 6,
    max_direct_link_ads_per_session INTEGER DEFAULT 3,
    
    -- Adsterra settings
    adsterra_direct_link TEXT DEFAULT 'https://www.profitablecpmnetwork.com/g8nhym4yg?key=2b71bf819cb8c5c7f8e011b7b75ea097',
    adsterra_direct_link_enabled BOOLEAN DEFAULT true,
    adsterra_banner_code TEXT DEFAULT '<script type="text/javascript">
	atOptions = {
		''key'' : ''2a86a3b22e8c1477e8a83d56c0386bb3'',
		''format'' : ''iframe'',
		''height'' : 90,
		''width'' : 728,
		''params'' : {}
	};
</script>
<script type="text/javascript" src="//judicialphilosophical.com/2a86a3b22e8c1477e8a83d56c0386bb3/invoke.js"></script>',
    adsterra_banner_enabled BOOLEAN DEFAULT true,
    adsterra_native_banner_code TEXT DEFAULT '',
    adsterra_native_banner_enabled BOOLEAN DEFAULT false,
    adsterra_social_bar_code TEXT DEFAULT '',
    adsterra_social_bar_enabled BOOLEAN DEFAULT false,
    adsterra_popunder_code TEXT DEFAULT '',
    adsterra_popunder_enabled BOOLEAN DEFAULT false,
    
    -- Monetag settings
    monetag_direct_link TEXT DEFAULT '',
    monetag_direct_link_enabled BOOLEAN DEFAULT false,
    monetag_banner_code TEXT DEFAULT '',
    monetag_banner_enabled BOOLEAN DEFAULT false,
    monetag_native_banner_code TEXT DEFAULT '',
    monetag_native_banner_enabled BOOLEAN DEFAULT false,
    monetag_social_bar_code TEXT DEFAULT '',
    monetag_social_bar_enabled BOOLEAN DEFAULT false,
    monetag_popunder_code TEXT DEFAULT '',
    monetag_popunder_enabled BOOLEAN DEFAULT false,
    
    -- Additional ad settings
    messages_per_ad_trigger INTEGER DEFAULT 7,
    inactivity_ad_timeout_ms INTEGER DEFAULT 45000,
    inactivity_ad_chance REAL DEFAULT 0.25,
    user_media_interstitial_chance REAL DEFAULT 0.15
);

-- ===================================================================
-- STEP 4: ENABLE ROW LEVEL SECURITY
-- ===================================================================

ALTER TABLE public.messages_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_activity_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_configurations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ad_settings ENABLE ROW LEVEL SECURITY;

-- ===================================================================
-- STEP 5: CREATE POLICIES
-- ===================================================================

-- Messages log policies
CREATE POLICY "Allow anon inserts for message logging" ON public.messages_log
FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow anon reads for analytics" ON public.messages_log
FOR SELECT USING (true);

-- Daily activity policies
CREATE POLICY "Allow anon inserts for daily activity" ON public.daily_activity_log
FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow anon reads for DAU analytics" ON public.daily_activity_log
FOR SELECT USING (true);

-- App configurations policies
CREATE POLICY "Allow anon reads for app configurations" ON public.app_configurations
FOR SELECT USING (true);

CREATE POLICY "Allow anon inserts for app configurations" ON public.app_configurations
FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow anon updates for app configurations" ON public.app_configurations
FOR UPDATE USING (true) WITH CHECK (true);

-- Ad settings policies
CREATE POLICY "Allow read access to ad_settings" ON public.ad_settings
FOR SELECT USING (true);

CREATE POLICY "Allow authenticated users to update ad_settings" ON public.ad_settings
FOR UPDATE TO authenticated USING (true);

CREATE POLICY "Allow authenticated users to insert ad_settings" ON public.ad_settings
FOR INSERT TO authenticated WITH CHECK (true);

-- ===================================================================
-- STEP 6: CREATE FUNCTIONS
-- ===================================================================

-- Update trigger function
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = TIMEZONE('utc'::text, NOW());
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create trigger for ad_settings
CREATE TRIGGER update_ad_settings_updated_at BEFORE UPDATE ON public.ad_settings
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Analytics functions
CREATE OR REPLACE FUNCTION get_daily_message_counts(start_date DATE)
RETURNS TABLE(date DATE, messages BIGINT)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    DATE_TRUNC('day', ml.created_at AT TIME ZONE 'UTC')::DATE AS date,
    COUNT(ml.id) AS messages
  FROM public.messages_log ml
  WHERE (ml.created_at AT TIME ZONE 'UTC')::DATE >= start_date
  GROUP BY DATE_TRUNC('day', ml.created_at AT TIME ZONE 'UTC')
  ORDER BY date ASC;
END;
$$;

CREATE OR REPLACE FUNCTION get_daily_active_user_counts(start_date DATE)
RETURNS TABLE(date DATE, active_users BIGINT)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    dal.activity_date AS date,
    COUNT(DISTINCT dal.user_pseudo_id) AS active_users
  FROM public.daily_activity_log dal
  WHERE dal.activity_date >= start_date
  GROUP BY dal.activity_date
  ORDER BY date ASC;
END;
$$;

-- Grant permissions
GRANT EXECUTE ON FUNCTION get_daily_message_counts(DATE) TO anon;
GRANT EXECUTE ON FUNCTION get_daily_active_user_counts(DATE) TO anon;

-- ===================================================================
-- STEP 7: INSERT DEFAULT DATA
-- ===================================================================

-- Insert default ad settings into ad_settings table
INSERT INTO public.ad_settings (
    ads_enabled_globally,
    max_direct_link_ads_per_day,
    max_direct_link_ads_per_session,
    adsterra_direct_link,
    adsterra_direct_link_enabled,
    adsterra_banner_code,
    adsterra_banner_enabled,
    messages_per_ad_trigger,
    inactivity_ad_timeout_ms,
    inactivity_ad_chance,
    user_media_interstitial_chance
) 
SELECT 
    true,
    6,
    3,
    'https://www.profitablecpmnetwork.com/g8nhym4yg?key=2b71bf819cb8c5c7f8e011b7b75ea097',
    true,
    '<script type="text/javascript">
	atOptions = {
		''key'' : ''2a86a3b22e8c1477e8a83d56c0386bb3'',
		''format'' : ''iframe'',
		''height'' : 90,
		''width'' : 728,
		''params'' : {}
	};
</script>
<script type="text/javascript" src="//judicialphilosophical.com/2a86a3b22e8c1477e8a83d56c0386bb3/invoke.js"></script>',
    true,
    7,
    45000,
    0.25,
    0.15
WHERE NOT EXISTS (SELECT 1 FROM public.ad_settings);

-- Insert initial ad settings configuration in app_configurations (for compatibility)
INSERT INTO public.app_configurations (id, settings) VALUES (
  'ad_settings_kruthika_chat_v1', 
  '{
    "adsEnabledGlobally": true,
    "adsterraDirectLink": "https://www.profitablecpmnetwork.com/g8nhym4yg?key=2b71bf819cb8c5c7f8e011b7b75ea097",
    "adsterraDirectLinkEnabled": true,
    "adsterraBannerCode": "<script type=\"text/javascript\">\n\tatOptions = {\n\t\t''key'' : ''2a86a3b22e8c1477e8a83d56c0386bb3'',\n\t\t''format'' : ''iframe'',\n\t\t''height'' : 90,\n\t\t''width'' : 728,\n\t\t''params'' : {}\n\t};\n</script>\n<script type=\"text/javascript\" src=\"//judicialphilosophical.com/2a86a3b22e8c1477e8a83d56c0386bb3/invoke.js\"></script>",
    "adsterraBannerEnabled": true,
    "adsterraNativeBannerCode": "",
    "adsterraNativeBannerEnabled": false,
    "adsterraSocialBarCode": "",
    "adsterraSocialBarEnabled": false,
    "adsterraPopunderCode": "",
    "adsterraPopunderEnabled": false,
    "monetagDirectLink": "",
    "monetagDirectLinkEnabled": false,
    "monetagBannerCode": "",
    "monetagBannerEnabled": false,
    "monetagNativeBannerCode": "",
    "monetagNativeBannerEnabled": false,
    "monetagSocialBarCode": "",
    "monetagSocialBarEnabled": false,
    "monetagPopunderCode": "",
    "monetagPopunderEnabled": false,
    "maxDirectLinkAdsPerDay": 6,
    "maxDirectLinkAdsPerSession": 3,
    "messagesPerAdTrigger": 7,
    "inactivityAdTimeoutMs": 45000,
    "inactivityAdChance": 0.25,
    "userMediaInterstitialChance": 0.15
  }'
) ON CONFLICT (id) DO UPDATE SET 
  settings = EXCLUDED.settings,
  updated_at = NOW();

-- Insert default AI profile
INSERT INTO public.app_configurations (id, settings)
VALUES ('ai_profile_kruthika_chat_v1', '{
  "name": "Kruthika",
  "avatarUrl": "https://i.postimg.cc/52S3BZrM/images-10.jpg",
  "status": "🌸 Tumse baat karne ka wait kar rahi hun! Let'\''s chat! 🌸",
  "statusStoryText": "Ask me anything! 💬 Main hamesha available hun!",
  "statusStoryImageUrl": "https://i.postimg.cc/52S3BZrM/images-10.jpg",
  "statusStoryHasUpdate": true
}')
ON CONFLICT (id) DO NOTHING;

-- ===================================================================
-- DATABASE SETUP COMPLETE
-- ===================================================================
```
